### ISSUE TITLE
Reconnect after los of connection doesn't work

### ISSUE THREAD

**Issue by staal-it** [vieapps/Enyim.Caching#1]
Hi there,

I've written a little demo application and try to run my program, shut-down the memcached server, start it again and hoped to see my application reconnecting to the cache. Only it doesn't. What am I missing here?

Here's the application: https://github.com/staal-it/MemcachedDemo. I'm running Memcached on Windows, version 1.4.5.

This is how I setup my client (not from config):
```c#
public MemcacedCache()
{

            _logger = new Logger();

            var config = new MemcachedClientConfiguration();

            config.Servers.Add(new IPEndPoint(IPAddress.Parse("127.0.0.1"), 11211));

            config.Protocol = MemcachedProtocol.Binary;

            _client = new MemcachedClient(null, config);
        }
```

**Comment by quynh-ng** [comment]
Hi,
The recovery timer will start automatically on NEXT HIT to memcached server (when aquires a socket from pool). That means if your app does nothing with memcached client, then nothing happend.

Please run the code below to see the detail logs (use the NuGet package named Microsoft.Extensions.Logging.Console)

```csharp
var logLevel = LogLevel.Debug;
var loggerFactory = new ServiceCollection()
	.AddLogging(builder => builder.SetMinimumLevel(logLevel))
	.BuildServiceProvider()
	.GetService<ILoggerFactory>()
	.AddConsole(logLevel);
var logger = loggerFactory.CreateLogger(typeof(Program));

Action doTest = () =>
{
	var config = new MemcachedClientConfiguration(loggerFactory);
	config.Servers.Add(new IPEndPoint(IPAddress.Parse("127.0.0.1"), 11211));
	config.Protocol = MemcachedProtocol.Binary;

	var client = new MemcachedClient(loggerFactory, config);
	var key = "demo-key";

	logger.LogInformation($"get value ==> {client.Get<string>(key)}");
	logger.LogInformation($"store value ==> {client.Store(StoreMode.Set, key, "value to cache", TimeSpan.FromMinutes(15))}");

	logger.LogInformation("press any to re-get => you need to STOP your memcached server at this point and see the logs...");
	Console.ReadKey();
	logger.LogInformation($"re-get value ==> {client.Get<string>(key)}");

	logger.LogInformation("press any to re-get again (you need to re-start your memcached server at this point, and see the logs while recovery working)...");
	Console.ReadKey();
	logger.LogInformation($"re-get value ==> {client.Get<string>(key)}");

	logger.LogInformation("press any to destroy...");
	Console.ReadKey();
	logger.LogWarning("destroyed...");
};

doTest();
var input = Console.ReadLine();
while (input != "exit")
{
	if (input.IsEquals("reset"))
		doTest();
	input = Console.ReadLine();
}
```
Here my logs:

----
info: TestNETCore.Program[0]
      Type 'exit' to exit, 'reset' to reset....
info: Enyim.Caching.MemcachedClient[0]
      An instance of Memcached client was created successful
info: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Pool has been initialized for 127.0.0.1:11211 with 10 sockets
dbug: Enyim.Caching.Memcached.IMemcachedNode[0]
      Cost for initiaizing pool: 334.8196ms
dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Acquiring stream from pool (127.0.0.1:11211)
dbug: Enyim.Caching.Memcached.PooledSocket[0]
      Socket was reset (454a81e0-7d40-4dcb-8aa2-6ab0edc51634)
dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Socket was reset (454a81e0-7d40-4dcb-8aa2-6ab0edc51634)
dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Releasing socket (454a81e0-7d40-4dcb-8aa2-6ab0edc51634) - Alive: True
info: TestNETCore.Program[0]
      get value ==>
dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Acquiring stream from pool (127.0.0.1:11211)
dbug: Enyim.Caching.Memcached.PooledSocket[0]
      Socket was reset (454a81e0-7d40-4dcb-8aa2-6ab0edc51634)
dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Socket was reset (454a81e0-7d40-4dcb-8aa2-6ab0edc51634)
dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Releasing socket (454a81e0-7d40-4dcb-8aa2-6ab0edc51634) - Alive: True
info: TestNETCore.Program[0]
      store value ==> True
info: TestNETCore.Program[0]
      press any to re-get => you need to STOP one of your memcached servers at this point and see the logs (try twice times to known which server that store cached)...
 dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Acquiring stream from pool (127.0.0.1:11211)
dbug: Enyim.Caching.Memcached.PooledSocket[0]
      Socket was reset (454a81e0-7d40-4dcb-8aa2-6ab0edc51634)
dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Socket was reset (454a81e0-7d40-4dcb-8aa2-6ab0edc51634)
fail: Enyim.Caching.Memcached.Protocol.Binary.BinaryResponse[0]
      Read: Error occurred while reading socket
System.IO.IOException: Failed to read from the socket '127.0.0.1:11211'. Error: ?
   at Enyim.Caching.Memcached.PooledSocket.Receive(Byte[] buffer, Int32 offset, Int32 count) in C:\Components\Enyim.Caching\Memcached\PooledSocket.cs:line 295
   at Enyim.Caching.Memcached.Protocol.Binary.BinaryResponse.Read(PooledSocket socket) in C:\Components\Enyim.Caching\Memcached\Protocol\Binary\BinaryResponse.cs:line 63
fail: Enyim.Caching.Memcached.IMemcachedNode[0]
      Failed to execute an operation
System.IO.IOException: Failed to read from the socket '127.0.0.1:11211'. Error: ?
   at Enyim.Caching.Memcached.Protocol.Binary.BinaryResponse.Read(PooledSocket socket) in C:\Components\Enyim.Caching\Memcached\Protocol\Binary\BinaryResponse.cs:line 79
   at Enyim.Caching.Memcached.Protocol.Binary.BinarySingleItemOperation.ReadResponse(PooledSocket socket) in C:\Components\Enyim.Caching\Memcached\Protocol\Binary\BinarySingleItemOperation.cs:line 25
   at Enyim.Caching.Memcached.MemcachedNode.ExecuteOperation(IOperation op) in C:\Components\Enyim.Caching\Memcached\MemcachedNode.cs:line 550
dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Releasing socket (454a81e0-7d40-4dcb-8aa2-6ab0edc51634) - Alive: True
info: TestNETCore.Program[0]
      re-get value ==>
info: TestNETCore.Program[0]
      press any to re-get again (you need to re-start your memcached server at this point and see the logs)...
ndbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Acquiring stream from pool (127.0.0.1:11211)
dbug: Enyim.Caching.Memcached.PooledSocket[0]
      Socket was reset (454a81e0-7d40-4dcb-8aa2-6ab0edc51634)
dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Socket was reset (454a81e0-7d40-4dcb-8aa2-6ab0edc51634)
fail: Enyim.Caching.Memcached.IMemcachedNode[0]
      Failed to execute an operation
System.IO.IOException: Failed to write to the socket '127.0.0.1:11211'. Error: ConnectionAborted
   at Enyim.Caching.Memcached.PooledSocket.Send(IList`1 buffers) in C:\Components\Enyim.Caching\Memcached\PooledSocket.cs:line 235
   at Enyim.Caching.Memcached.MemcachedNode.ExecuteOperation(IOperation op) in C:\Components\Enyim.Caching\Memcached\MemcachedNode.cs:line 543
dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Releasing socket (454a81e0-7d40-4dcb-8aa2-6ab0edc51634) - Alive: True
dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Mark as dead was requested (127.0.0.1:11211)
dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      FailurePolicy.ShouldFail(): True
warn: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Marking node 127.0.0.1:11211 is dead
dbug: Enyim.Caching.Memcached.DefaultServerPool[0]
      Node 127.0.0.1:11211 is dead
dbug: Enyim.Caching.Memcached.DefaultServerPool[0]
      Starting the recovery timer
dbug: Enyim.Caching.Memcached.DefaultServerPool[0]
      Recovery timer is started
info: TestNETCore.Program[0]
      re-get value ==>
info: TestNETCore.Program[0]
      press any to destroy...
warn: TestNETCore.Program[0]
      destroyed...
dbug: Enyim.Caching.Memcached.DefaultServerPool[0]
      Checking the dead servers
dbug: Enyim.Caching.Memcached.DefaultServerPool[0]
      Dead: 127.0.0.1:11211
fail: Enyim.Caching.Memcached.IMemcachedNode[0]
      Cannot create socket (127.0.0.1:11211)
System.TimeoutException: Could not connect to 127.0.0.1:11211
   at Enyim.Caching.Memcached.PooledSocket.TryConnect(Socket socket, EndPoint endpoint, Int32 timeout) in C:\Components\Enyim.Caching\Memcached\PooledSocket.cs:line 81
   at Enyim.Caching.Memcached.PooledSocket..ctor(EndPoint endpoint, TimeSpan connectionTimeout, TimeSpan receiveTimeout) in C:\Components\Enyim.Caching\Memcached\PooledSocket.cs:line 49
   at Enyim.Caching.Memcached.MemcachedNode.CreateSocket() in C:\Components\Enyim.Caching\Memcached\MemcachedNode.cs:line 163
dbug: Enyim.Caching.Memcached.DefaultServerPool[0]
      Still dead
dbug: Enyim.Caching.Memcached.DefaultServerPool[0]
      Count of dead is 1, starting the timer.
dbug: Enyim.Caching.Memcached.DefaultServerPool[0]
      Checking the dead servers
dbug: Enyim.Caching.Memcached.DefaultServerPool[0]
      Dead: 127.0.0.1:11211
fail: Enyim.Caching.Memcached.IMemcachedNode[0]
      Cannot create socket (127.0.0.1:11211)
System.TimeoutException: Could not connect to 127.0.0.1:11211
   at Enyim.Caching.Memcached.PooledSocket.TryConnect(Socket socket, EndPoint endpoint, Int32 timeout) in C:\Components\Enyim.Caching\Memcached\PooledSocket.cs:line 81
   at Enyim.Caching.Memcached.PooledSocket..ctor(EndPoint endpoint, TimeSpan connectionTimeout, TimeSpan receiveTimeout) in C:\Components\Enyim.Caching\Memcached\PooledSocket.cs:line 49
   at Enyim.Caching.Memcached.MemcachedNode.CreateSocket() in C:\Components\Enyim.Caching\Memcached\MemcachedNode.cs:line 163
dbug: Enyim.Caching.Memcached.DefaultServerPool[0]
      Still dead
dbug: Enyim.Caching.Memcached.DefaultServerPool[0]
      Count of dead is 1, starting the timer.
dbug: Enyim.Caching.Memcached.DefaultServerPool[0]
      Checking the dead servers
dbug: Enyim.Caching.Memcached.DefaultServerPool[0]
      Dead: 127.0.0.1:11211
info: Enyim.Caching.Memcached.IMemcachedNode[0]
      Try to connect to the server: 127.0.0.1:11211
dbug: Enyim.Caching.Memcached.DefaultServerPool[0]
      Ping OK, go back alive
dbug: Enyim.Caching.Memcached.DefaultServerPool[0]
      Reinitializing the locator
dbug: Enyim.Caching.Memcached.DefaultServerPool[0]
      Count of dead is 0, stopping the timer.

**Comment by staal-it** [comment]
Thanks for your quick reply! Your version works fine. However it seems to fail when using async methods. The following code gives errors:

```c#
internal class Program
   {
      static void Main(string[] args)
      {
            MainAsync(args).GetAwaiter().GetResult();
      }

      static async Task MainAsync(string[] args)
      {
            var logLevel = LogLevel.Debug;
            var loggerFactory = new ServiceCollection()
                .AddLogging(builder => builder.SetMinimumLevel(logLevel))
                .BuildServiceProvider()
                .GetService<ILoggerFactory>()
                .AddConsole(logLevel);
            var logger = loggerFactory.CreateLogger(typeof(Program));

            var config = new MemcachedClientConfiguration(loggerFactory);
            config.Servers.Add(new System.Net.IPEndPoint(IPAddress.Parse("127.0.0.1"), 11211));
            config.Protocol = MemcachedProtocol.Binary;

            var client = new MemcachedClient(loggerFactory, config);
            var key = "demo-key";

            logger.LogInformation($"get value ==> {client.Get<string>(key)}");
            logger.LogInformation($"store value ==> {client.Store(StoreMode.Set, key, "value to cache", TimeSpan.FromMinutes(15))}");

            logger.LogInformation("press any to re-get => you need to STOP your memcached server at this point and see the logs...");
            Console.ReadKey();
            logger.LogInformation($"re-get value ==> {await client.GetAsync<string>(key)}");

            logger.LogInformation("press any to re-get again (you need to re-start your memcached server at this point, and see the logs while recovery working)...");
            Console.ReadKey();
            logger.LogInformation($"re-get value ==> {await client.GetAsync<string>(key)}");

            logger.LogInformation("press any to destroy...");
            Console.ReadKey();
            logger.LogWarning("destroyed...");
            
            var input = Console.ReadLine();
        }
    }
```
Here's the log:

info: Enyim.Caching.MemcachedClient[0]
      An instance of Memcached client was created successful
info: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Pool has been initialized for 127.0.0.1:11211 with 10 sockets
dbug: Enyim.Caching.Memcached.IMemcachedNode[0]
      Cost for initiaizing pool: 15.0063ms
dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Acquiring stream from pool (127.0.0.1:11211)
dbug: Enyim.Caching.Memcached.PooledSocket[0]
      Socket was reset (2a8d9a39-1a40-480e-91c5-5acfc1103859)
dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Socket was reset (2a8d9a39-1a40-480e-91c5-5acfc1103859)
dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Releasing socket (2a8d9a39-1a40-480e-91c5-5acfc1103859) - Alive: True
info: MemcachedTryout.Program[0]
      get value ==>
dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Acquiring stream from pool (127.0.0.1:11211)
dbug: Enyim.Caching.Memcached.PooledSocket[0]
      Socket was reset (2a8d9a39-1a40-480e-91c5-5acfc1103859)
dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Socket was reset (2a8d9a39-1a40-480e-91c5-5acfc1103859)
dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Releasing socket (2a8d9a39-1a40-480e-91c5-5acfc1103859) - Alive: True
info: MemcachedTryout.Program[0]
      store value ==> True
info: MemcachedTryout.Program[0]
      press any to re-get => you need to STOP your memcached server at this point and see the logs...
dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Acquiring stream from pool (127.0.0.1:11211)
dbug: Enyim.Caching.Memcached.PooledSocket[0]
      Socket was reset (2a8d9a39-1a40-480e-91c5-5acfc1103859)
dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Socket was reset (2a8d9a39-1a40-480e-91c5-5acfc1103859)
fail: Enyim.Caching.Memcached.IMemcachedNode[0]
      Failed to execute an operation (async)
System.IO.IOException: Failed to write to the socket '127.0.0.1:11211'. Error: ConnectionReset
   at Enyim.Caching.Memcached.PooledSocket.<SendAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Enyim.Caching.Memcached.MemcachedNode.<ExecuteOperationAsync>d__27.MoveNext()
dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Releasing socket (2a8d9a39-1a40-480e-91c5-5acfc1103859) - Alive: True
info: MemcachedTryout.Program[0]
      re-get value ==>
info: MemcachedTryout.Program[0]
      press any to re-get again (you need to re-start your memcached server at this point, and see the logs while recovery working)...
dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Acquiring stream from pool (127.0.0.1:11211)
dbug: Enyim.Caching.Memcached.PooledSocket[0]
      Socket was reset (2a8d9a39-1a40-480e-91c5-5acfc1103859)
dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Socket was reset (2a8d9a39-1a40-480e-91c5-5acfc1103859)
fail: Enyim.Caching.Memcached.IMemcachedNode[0]
      Failed to execute an operation (async)
System.IO.IOException: Failed to write to the socket '127.0.0.1:11211'. Error: ConnectionReset
   at Enyim.Caching.Memcached.PooledSocket.<SendAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Enyim.Caching.Memcached.MemcachedNode.<ExecuteOperationAsync>d__27.MoveNext()
dbug: Enyim.Caching.Memcached.MemcachedNode.InternalPoolImpl[0]
      Releasing socket (2a8d9a39-1a40-480e-91c5-5acfc1103859) - Alive: True
info: MemcachedTryout.Program[0]
      re-get value ==>
info: MemcachedTryout.Program[0]
      press any to destroy...

**Comment by quynh-ng** [comment]
While watching match Real Madrid vs Juventus (and congrats to Real Madrid), I found a bug that not mark a node is dead when got error. Then new NuGet package was release to fix its, please update (https://www.nuget.org/packages/VIEApps.Enyim.Caching/1.4.4.1804).

And remember, the recovery timer will start when a mode is dead at the next time when your app does something with memcached client.

**Comment by staal-it** [comment]
What a match!

You are awesome! Works after the update!
